[package]
name = "oxidehtf-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
inventory = "0.3.20"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["extra-traits", "full"] }
